# This name is shown in status badges
name: build

on:
  push:
    branches-ignore:
      - 'tmp**'
  pull_request:
    branches-ignore:
      - 'tmp**'

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Install dependencies
      run: yarn install

    - name: Build package
      run: yarn build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test
